disable_distribution: true
dataset_name: ['lipo']
dummy_size: -1 # work with a small subset of original dataset
target: [ 'exp']
num_conformers: 5
prune_conformers: false
batch_size: 72
experiment: conan_fgw.src.experiments.SOTAExperiment
num_epochs: 200
early_stopping:
  min_delta: 0.0001
  patience: 150
learning_rate: 0.001
use_lr_finder: false
use_wandb: false