disable_distribution: false
dataset_name: ['lipo']
dummy_size: -1 # work with a small subset of original dataset
target: [ 'exp']
num_conformers: 3
prune_conformers: false
batch_size: 36
experiment: conan_fgw.src.experiments.SOTAExperimentBaryCenter
num_epochs: 1 # 90
early_stopping:
  min_delta: 0.0001
  patience: 70
learning_rate: 0.0005
use_lr_finder: false
use_wandb: false
max_iter: 100