name: conan
channels:
  - conda-forge
dependencies:
  - python=3.9
  - black
  - flake8
  - isort
  - pip
  - pip:
    - python-dotenv
    - absl-py==2.0.0
    - aiohttp==3.9.1
    - aiosignal==1.3.1
    - alabaster==0.7.13
    - annotated-types==0.6.0
    - appdirs==1.4.4
    - asttokens==2.4.1
    - async-timeout==4.0.3
    - attrs==23.1.0
    - autopep8==2.0.4
    - babel==2.14.0
    - blessed==1.20.0
    - cachetools==5.3.2
    - chardet==5.2.0
    - charset-normalizer==3.3.2
    - click==8.1.7
    - cmake==3.28.1
    - comm==0.2.1
    - contourpy==1.2.0
    - cycler==0.12.1
    - debugpy==1.8.0
    - decorator==5.1.1
    - docker-pycreds==0.4.0
    - docutils==0.20.1
    - exceptiongroup==1.2.0
    - executing==2.0.1
    - filelock==3.13.1
    - fonttools==4.47.0
    - frozenlist==1.4.1
    - fsspec==2023.12.2
    - gitdb==4.0.11
    - gitpython==3.1.40
    - google-auth==2.25.2
    - google-auth-oauthlib==1.2.0
    - gpustat==1.1.1
    - grpcio==1.60.0
    - idna==3.6
    - imageio==2.33.1
    - imagesize==1.4.1
    - importlib-metadata==7.0.1
    - importlib-resources==6.1.1
    - ipykernel==6.28.0
    - ipython==8.18.1
    - isort==5.13.2
    - jedi==0.19.1
    - jinja2==3.1.2
    - joblib==1.3.2
    - jsonargparse==4.20.1
    - jupyter-client==8.6.0
    - jupyter-core==5.6.1
    - kiwisolver==1.4.5
    - lazy-loader==0.3
    - lightning-utilities==0.10.0
    - lit==17.0.6
    - littleutils==0.2.2
    - markdown==3.5.1
    - markupsafe==2.1.3
    - matplotlib==3.7.3
    - matplotlib-inline==0.1.6
    - mpmath==1.3.0
    - multidict==6.0.4
    - nest-asyncio==1.5.8
    - networkx==3.2.1
    - numpy==1.24.4
    - numpydoc==1.6.0
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-ml-py==12.535.133
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nccl-cu12==2.18.1
    - nvidia-nvjitlink-cu12==12.3.101
    - nvidia-nvtx-cu11==11.7.91
    - nvidia-nvtx-cu12==12.1.105
    - oauthlib==3.2.2
    - ogb==1.3.6
    - opencv-python==4.9.0.80
    - outdated==0.2.2
    - packaging==23.2
    - pandas==2.0.0
    - parso==0.8.3
    - pathtools==0.1.2
    - pexpect==4.9.0
    - pillow==10.1.0
    - platformdirs==4.1.0
    - pot==0.8.2
    - prettytable==3.7.0
    - prompt-toolkit==3.0.43
    - protobuf==4.23.4
    - psutil==5.9.7
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - py3dmol==2.0.4
    - pyasn1==0.5.1
    - pyasn1-modules==0.3.0
    - pycodestyle==2.11.1
    - pydantic==2.5.3
    - pydantic-core==2.14.6
    - pygments==2.17.2
    - pyparsing==3.1.1
    - python-dateutil==2.8.2
    - pytorch-lightning==2.0.1
    - pytz==2023.3.post1
    - pyyaml==6.0.1
    - pyzmq==25.1.2
    - rdkit==2022.9.5
    - rdkit-pypi==2022.9.5
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - ruamel-yaml==0.18.5
    - ruamel-yaml-clib==0.2.8
    - scikit-image==0.22.0
    - scikit-learn==1.3.2
    - scikit-learn-extra==0.3.0
    - sentry-sdk==1.39.1
    - setproctitle==1.3.3
    - six==1.16.0
    - smmap==5.0.1
    - snowballstemmer==2.2.0
    - sphinx==7.2.6
    - sphinxcontrib-applehelp==1.0.7
    - sphinxcontrib-devhelp==1.0.5
    - sphinxcontrib-htmlhelp==2.0.4
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.6
    - sphinxcontrib-serializinghtml==1.1.9
    - stack-data==0.6.3
    - sympy==1.12
    - tabulate==0.9.0
    - tensorboard==2.15.1
    - tensorboard-data-server==0.7.2
    - threadpoolctl==3.2.0
    - tifffile==2023.12.9
    - tomli==2.0.1
    - torch==2.0.0
    - torch-cluster==1.6.1
    - torch-geometric==2.3.0
    - torch-scatter==2.1.2
    - torch-sparse==0.6.18
    - torch-spline-conv==1.2.2
    - torchmetrics==1.2.1
    - tornado==6.4
    - tqdm==4.66.1
    - traitlets==5.14.1
    - triton==2.0.0
    - typer==0.9.0
    - typing-extensions==4.9.0
    - tzdata==2023.3
    - urllib3==2.1.0
    - wandb==0.14.2
    - wcwidth==0.2.12
    - werkzeug==3.0.1
    - yarl==1.9.4
    - zipp==3.17.0