disable_distribution: true
dataset_name: ['freesolv']
dummy_size: -1 # work with a small subset of original dataset
target: [ 'expt']
num_conformers: 10
prune_conformers: false
batch_size: 32
experiment: conan_fgw.src.experiments.SOTAExperiment
num_epochs: 200
early_stopping:
  min_delta: 0.0001
  patience: 50
learning_rate: 0.001 # LR to start with
use_lr_finder: false
use_wandb: false