disable_distribution: false
dataset_name: ['freesolv']
dummy_size: -1
target: [ 'expt']
num_conformers: 5
prune_conformers: false
batch_size: 24
experiment: conan_fgw.src.experiments.SOTAExperimentBaryCenter
num_epochs: 70
early_stopping:
  min_delta: 0.0001
  patience: 50
learning_rate: 0.0005
use_lr_finder: false
use_wandb: false
agg_weight: 0.2