disable_distribution: false
dataset_name: ['esol']
dummy_size: -1 # work with a small subset of original dataset
target: [ 'measured_log_sol']
num_conformers: 5
prune_conformers: false
batch_size: 24 # 20 (for 5 gpus)
experiment: conan_fgw.src.experiments.SOTAExperimentBaryCenter
num_epochs: 80
early_stopping:
  min_delta: 0.0001
  patience: 50
learning_rate: 0.0005
use_lr_finder: false
use_wandb: false

