disable_distribution: false
dataset_name: ['bace']
dummy_size: -1
target: [ 'pIC50']
num_conformers: 5
prune_conformers: false
batch_size: 18
experiment: conan_fgw.src.experiments.SOTAExperimentBaryCenter
num_epochs: 60
early_stopping:
  min_delta: 0.0001
  patience: 40
learning_rate: 0.0005
use_lr_finder: false
use_wandb: false
agg_weight: 0.2